### ISSUE TITLE
renderPartial should accept an array of base templates

### ISSUE THREAD

**Issue by mjreich** [nxus/templater#2]
And render recursively…

```
app.get(‘templater’).request(‘renderPartial’, ‘some-partial’, [‘intermediate-template’, ‘base-template’], args)
```

Render order is then:
* some-partial
* intermediate-template
* base-template

**Comment by loppear** [comment]
Going to wish we were specifying this in the templates (in a jekyll-like front-matter) rather than at render time, but agree with the need.
